# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VirtualStickDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VirtualStickDemo
  pod 'DJI-SDK-iOS', '~> 4.5’

  target 'VirtualStickDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VirtualStickDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
